# Generated by Django 3.2.4 on 2021-06-23 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='electricas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=200, null=True)),
                ('modelo', models.CharField(default='', max_length=200, null=True)),
                ('precio', models.CharField(default='', max_length=200, null=True)),
                ('fecha', models.CharField(default='', max_length=200, null=True)),
                ('marca', models.CharField(default='', max_length=200, null=True)),
                ('imagen', models.ImageField(null='True', upload_to='imagen')),
            ],
        ),
        migrations.CreateModel(
            name='manuales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=200, null=True)),
                ('modelo', models.CharField(default='', max_length=200, null=True)),
                ('precio', models.CharField(default='', max_length=200, null=True)),
                ('fecha', models.CharField(default='', max_length=200, null=True)),
                ('marca', models.CharField(default='', max_length=200, null=True)),
                ('imagen', models.ImageField(null='True', upload_to='imagen')),
            ],
        ),
        migrations.CreateModel(
            name='neumaticas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=200, null=True)),
                ('modelo', models.CharField(default='', max_length=200, null=True)),
                ('precio', models.CharField(default='', max_length=200, null=True)),
                ('fecha', models.CharField(default='', max_length=200, null=True)),
                ('marca', models.CharField(default='', max_length=200, null=True)),
                ('imagen', models.ImageField(null='True', upload_to='imagen')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ferre.neumaticas')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
