# Generated by Django 3.2.4 on 2021-06-23 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ferre', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
