# Generated by Django 3.2.4 on 2021-06-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferre', '0003_auto_20210623_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='electricas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=200, null=True)),
                ('modelo', models.CharField(default='', max_length=200, null=True)),
                ('precio', models.CharField(default='', max_length=200, null=True)),
                ('fecha', models.CharField(default='', max_length=200, null=True)),
                ('marca', models.CharField(default='', max_length=200, null=True)),
                ('imagen', models.ImageField(null='True', upload_to='imagen')),
            ],
        ),
        migrations.CreateModel(
            name='manuales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=200, null=True)),
                ('modelo', models.CharField(default='', max_length=200, null=True)),
                ('precio', models.CharField(default='', max_length=200, null=True)),
                ('fecha', models.CharField(default='', max_length=200, null=True)),
                ('marca', models.CharField(default='', max_length=200, null=True)),
                ('imagen', models.ImageField(null='True', upload_to='imagen')),
            ],
        ),
        migrations.CreateModel(
            name='neumaticas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=200, null=True)),
                ('modelo', models.CharField(default='', max_length=200, null=True)),
                ('precio', models.CharField(default='', max_length=200, null=True)),
                ('fecha', models.CharField(default='', max_length=200, null=True)),
                ('marca', models.CharField(default='', max_length=200, null=True)),
                ('imagen', models.ImageField(null='True', upload_to='imagen')),
            ],
        ),
        migrations.DeleteModel(
            name='corona',
        ),
        migrations.DeleteModel(
            name='deportes',
        ),
        migrations.DeleteModel(
            name='nacionales',
        ),
    ]
